version = 1

test_patterns = [
  "Code/hexapod/tests/**",
  "test_*.py"
]

[[analyzers]]
name = "test-coverage"
enabled = true

name = "python"
enabled = true

  [analyzers.meta]
  runtime_version = "3.x.x"
