# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Generate_Report:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Report results to DeepSource
        run: |
          # Install pytest and pytest-cov pacakages from pip
          pip install pytest pytest-cov
          pip install numpy==1.22.3
          pip install pyserial==3.5
          # Run pytest with --cov and --cov-report flags
          pytest --cov=./ --cov-report xml
          # Install deepsource CLI
          curl https://deepsource.io/cli | sh
          # Generate coverage report in xml format
          coverage xml
          # From the root directory, run the report coverage command
          ./bin/deepsource report --analyzer test-coverage --key python --value-file ./coverage.xml

        env:
          DEEPSOURCE_DSN: ${{ secrets.DEEPSOURCE_DSN }}
          
      - name: Send Results to CodeCov
        run: |
          curl -Os https://uploader.codecov.io/latest/linux/codecov
          chmod +x codecov
          ./codecov
          
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
